const preferences = [
  {
    userId: 1,
    beerId: 5,
    malt: "Lager Malt",
    quantity: 6.63,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 1,
    beerId: 7,
    malt: "Extra Pale",
    quantity: 9.69,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 1,
    beerId: 15,
    malt: "Pale Ale - Tipple",
    quantity: 11.1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 2,
    beerId: 3,
    malt: "Propino Pale Malt",
    quantity: 1.63,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 2,
    beerId: 23,
    malt: "Extra Pale",
    quantity: 5.8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 2,
    beerId: 33,
    malt: "Extra Pale",
    quantity: 6.38,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 3,
    beerId: 4,
    malt: "Extra Pale",
    quantity: 4.58,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 3,
    beerId: 41,
    malt: "Pale Ale",
    quantity: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 3,
    beerId: 42,
    malt: "Extra Pale",
    quantity: 7.4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 5,
    beerId: 4,
    malt: "Extra Pale",
    quantity: 4.58,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 5,
    beerId: 41,
    malt: "Pale Ale",
    quantity: 9,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: 5,
    beerId: 42,
    malt: "Extra Pale",
    quantity: 7.4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
module.exports = preferences;
